/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mhame
 */
public class quizz2 extends javax.swing.JFrame {
  JLabel label = new JLabel("آسف ليس لديك النتيجة اللازمة للانتقال إلى الدرس التالي");
    /**
     * Creates new form quizz2
     */
    public quizz2() {
        initComponents();
          setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           label.setFont(new Font("Arial", Font.BOLD, 18));
    }
      String scores=null;
    String j=null;
            public void select()
{
     String sql ="Select score from table1 where username=? ";
//"Select * from table1 where username=? and password=?";

try
{  
    
    Class.forName("com.mysql.jdbc.Driver");
    
    Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1,Pass.s);
   // pst.setString(2,jTextField2.getText());
    
pst.execute();
    ResultSet rs = pst.executeQuery();

//s=rs.getString("username");
  //  System.out.println(s);
    if(rs.next())
        
   {
       scores=rs.getString("score");
       //JOptionPane.showMessageDialog(null,"Username and Password Accepted!"); 
       System.out.println(scores);
     //  Videos p=new Videos();
    //   p.setVisible(true);
  //    Question1 b=new Question1();
   //    b.setVisible(true);
       System.out.println("salut");
   }//else //JOptionPane.showMessageDialog(null,"Wrong Username and Password!");
}       catch (SQLException ex) {
        //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
       //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        
   // TODO add your handling code here:
                  
    }                                    
}
    public void select1()
{
     String sql ="Select score2 from table1 where username=? ";
//"Select * from table1 where username=? and password=?";

try
{  
    
    Class.forName("com.mysql.jdbc.Driver");
    
    Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1,Pass.s);
   // pst.setString(2,jTextField2.getText());
    
pst.execute();
    ResultSet rs = pst.executeQuery();

//s=rs.getString("username");
  //  System.out.println(s);
    if(rs.next())
        
   {
       j=rs.getString("score2");
       //JOptionPane.showMessageDialog(null,"Username and Password Accepted!"); 
       System.out.println(j);
      // Videos p=new Videos();
    //   p.setVisible(true);
  //    Question1 b=new Question1();
   //    b.setVisible(true);
       System.out.println("salut");
   }//else //JOptionPane.showMessageDialog(null,"Wrong Username and Password!");
}       catch (SQLException ex) {
        //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
       //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        
   // TODO add your handling code here:
                  
    }                                    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().setLayout(null);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("إختبار الدرس ١٤");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(570, 320, 250, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("إختبار الدرس ١٥");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(570, 450, 250, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("قائمة الإختبارات   ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 50, 200, 160);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("الرجوع إلى القائمة");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(580, 580, 240, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/back1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1310, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        Question1 x=new Question1();
        x.setVisible(true);
        // this.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // TODO add your handling code here:

        select();
        if(scores.equals("Score: 30"))
        {
            Question4 p=new Question4();
            p.setVisible(true);
            this.setVisible(false);} else JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        // TODO add your handling code here:
        principal x=new principal();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quizz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
