/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Mhame
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("إضافة الطالب الجديد");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 310, 200, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("حذف الطالب");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 380, 200, 32);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("نتائج  الطلبة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 540, 260, 34);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(660, 310, 130, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 310, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("كلمة السر الجديدة");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 300, 160, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("اسم  الطالب الجديد");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(810, 310, 140, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(350, 380, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("اسم  الطالب ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 390, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("مرحبا بكم في قائمة المسؤول");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 80, 360, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/back1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 980, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String sql ="insert into table1 (username,password,score,score1) values(?,?,?,?)";
        //"Select * from table1 where username=? and password=?";

        try
        {

            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField5.getText());
             pst.setString(4,jTextField5.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Student was successfully Add to the database");

            //ResultSet rs = pst.executeQuery();

            // if(rs.next())

            //  {

                //    Question1 b=new Question1();
                //     b.setVisible(true);
                // System.out.println("salut");
                //  }
        }       catch (SQLException ex) {
            //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);

            // TODO add your handling code here:

        }                                       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  String ide=jTextField1.getText();
        String sql ="delete from table1 where username=?";

        //"DELETE FROM table1 WHERE username = '"+ide+"' ";

        //"DELETE FROM table1 where (username,password) values(?,?)";
        //"Select * from table1 where username=? and password=?";
        System.out.println(sql);
        
  try
        {

            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,jTextField3.getText());
            //pst.setString(2,jTextField2.getText());

            pst.execute();
           JOptionPane.showMessageDialog(null,"Student was successfully DELETED from the database");

         // ResultSet rs = pst.executeQuery();

         /*   if(rs.next())

             {
 JOptionPane.showMessageDialog(null,"Data successfully Add to the database");
                //    Question1 b=new Question1();
                //     b.setVisible(true);
                System.out.println("salut");
                }else  JOptionPane.showMessageDialog(null,"Data to the database");*/
        }       catch (SQLException ex) {
            //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);

            // TODO add your handling code here:

        }                         //here:
                                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
 String sql ="Select score from table1 where username=?";
//"Select * from table1 where username=? and password=?";
Statement st= null;
ResultSet rs=null;
String s;

try
{  
    
    Class.forName("com.mysql.jdbc.Driver");
    
    Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
    st=con.createStatement();
    s="select * from table1";
    rs=st.executeQuery(s);
    ResultSetMetaData rsmt=rs.getMetaData();
    int c=rsmt.getColumnCount();
    Vector column=new Vector(c);
    for(int i=1;i<=c;i++)
    {
        column.add(rsmt.getColumnName(i));
    }
    Vector data=new Vector();
    Vector row=new Vector();
    while(rs.next())
    {
        row=new Vector(c);
        for(int i=1;i<=c;i++)
        {
            row.add(rs.getString(i));
        }
        data.add(row);
    }
 JFrame frame=new JFrame();
 
 frame.setSize(1500,1500);
 frame.setLocationRelativeTo(null);
 
 frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    JPanel panel=new JPanel();
    JTable table=new JTable(data,column);
    JScrollPane jsp=new JScrollPane(table);
    panel.setLayout(new BorderLayout());
    panel.add(jsp,BorderLayout.CENTER);
    frame.setContentPane(panel);
    frame.setVisible(true);
 
}       catch (Exception e) {
    JOptionPane.showMessageDialog(null,"Wrong Username and Password!");
        //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
       } finally {
    try{
        st.close();
        rs.close();
        
      
    
       //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        
   // TODO add your handling code here:
                  
    }catch(Exception e)   {     JOptionPane.showMessageDialog(null,"Wrong Username and Password!");                               
    }//GEN-LAST:event_jButton4ActionPerformed
}}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
