/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLDecoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.time.Clock.system;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.Stage;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static quizz.Pass.s;

/**
 *
 * @author Mhame
 */
public class Videos extends javax.swing.JFrame {

      JLabel label = new JLabel("آسف ليس لديك النتيجة اللازمة للانتقال إلى الدرس التالي");

         
    /**
     * Creates new form Videos
     */
    
    public Videos() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
   label.setFont(new Font("Arial", Font.BOLD, 18));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText(" الدرس ١٤ ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 330, 240, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText(" الدرس ١٥ ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 460, 240, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText(" الدرس ١٦ ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(540, 600, 240, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("قائمة الدروس");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 60, 200, 160);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("الرجوع إلى القائمة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(540, 730, 240, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizz/back1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1300, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  String decodedPath;
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//MediaPanel t=new MediaPanel(mp4.avi);
//AdvancedMedia i=new AdvancedMedia();
 try {
					//Desktop.getDesktop().open(new File("C:\\Users\\Mhame\\Documents\\NetBeansProjects\\quizz\\src\\l14.mp4"));
                                   Desktop.getDesktop().open(new File("l14.mp4"));
                                   
                             //      x.start();
                             //    Videos.class.getProtectionDomain().getCodeSource().getLocation()
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}      // T
    }    

//StartUpStartUpTest u=new StartUpStartUpTest();
//u.main(null);
   


			/*	 try {
					Desktop.getDesktop().open(new File("C:\\Users\\Mhame\\Documents\\NetBeansProjects\\quizz\\src\\quizz\\l14.mp4"));
                                   //     Desktop.getDesktop().open(new File("l14.mp4"));
                                   
                                   
                             //    Videos.class.getProtectionDomain().getCodeSource().getLocation()
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}      // TODO add your handling         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
*/
    
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      select();
       if(scores.equals("Score: 30"))
        {
       
        //this.setVisible(false);
                                            

                                         // TODO add your handling code here:
 try {
					//Desktop.getDesktop().open(new File("C:\\Users\\Mhame\\Documents\\NetBeansProjects\\quizz\\src\\l15.mp4"));
                                   Desktop.getDesktop().open(new File("l15.mp4"));
                                   
                             //      x.start();
                             //    Videos.class.getProtectionDomain().getCodeSource().getLocation()
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}      // T
        }else 
    JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);//JOptionPane.showMessageDialog(null,"آسف ليس لديك النتيجة اللازمة للانتقال إلى الدرس التالي"); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      select1();
        if(j.equals("Score: 20")){
         try {
					//Desktop.getDesktop().open(new File("C:\\Users\\Mhame\\Documents\\NetBeansProjects\\quizz\\src\\l16.mp4"));
                                  Desktop.getDesktop().open(new File("l16.mp4"));
                                   
                             //      x.start();
                             //    Videos.class.getProtectionDomain().getCodeSource().getLocation()
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}      // T
    }//GEN-LAST:event_jButton3ActionPerformed
else 
    JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);   }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
        principal x=new principal();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
     
    
      
String scores=null;
    String j=null;
        public void select()
{
     String sql ="Select score from table1 where username=? ";
//"Select * from table1 where username=? and password=?";

try
{  
    
    Class.forName("com.mysql.jdbc.Driver");
    
    Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1,Pass.s);
   // pst.setString(2,jTextField2.getText());
    
pst.execute();
    ResultSet rs = pst.executeQuery();

//s=rs.getString("username");
  //  System.out.println(s);
    if(rs.next())
        
   {
       scores=rs.getString("score");
       //JOptionPane.showMessageDialog(null,"Username and Password Accepted!"); 
       System.out.println(scores);
     //  Videos p=new Videos();
    //   p.setVisible(true);
  //    Question1 b=new Question1();
   //    b.setVisible(true);
       System.out.println("salut");
   }//else //JOptionPane.showMessageDialog(null,"Wrong Username and Password!");
}       catch (SQLException ex) {
        //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
       //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        
   // TODO add your handling code here:
                  
    }                                    
}
    
    public void select1()
{
     String sql ="Select score1 from table1 where username=? ";
//"Select * from table1 where username=? and password=?";

try
{  
    
    Class.forName("com.mysql.jdbc.Driver");
    
    Connection con = DriverManager.getConnection("jdbc:mysql://"+Pass.x+":3306/javademo?" + "user=root&password=");
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1,Pass.s);
   // pst.setString(2,jTextField2.getText());
    
pst.execute();
    ResultSet rs = pst.executeQuery();

//s=rs.getString("username");
  //  System.out.println(s);
    if(rs.next())
        
   {
       j=rs.getString("score1");
       //JOptionPane.showMessageDialog(null,"Username and Password Accepted!"); 
       System.out.println(j);
      // Videos p=new Videos();
    //   p.setVisible(true);
  //    Question1 b=new Question1();
   //    b.setVisible(true);
       System.out.println("salut");
   }//else //JOptionPane.showMessageDialog(null,"Wrong Username and Password!");
}       catch (SQLException ex) {
        //    Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
       //     Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        
   // TODO add your handling code here:
                  
    }                                    
}
    
                         //      System.out.println(Videos.class.getProtectionDomain().getCodeSource().getLocation()+"l14.mp4");

     /*    
      * 
     * @param args the command line argments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Videos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
